# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6af49d53556cc15291eaba1a294db29ab747cc53bdc1bfdf443e34e7db33a164979debddfbe5219a922cce4a530f0a0fa9b55f5ffe3a6ce42849b640eb9e5ea5

test:
  secret_key_base: 2f6fac8157b3d273f8834f09a8b45cdcab1319389952f27401eddf6714793957e8917d23841d5b3c5ec33a7acc3a97784cd4e94d4f0cab6ed0a94e20a49a08e9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
